### PR TITLE
Optimize socket read/write with array ptrs

### PR DESCRIPTION
**Pull request by armanbilge**
This is a nice optimization :)

### CODE REVIEW

**Comment by armanbilge** [comment]
Um ... @LeeTibbert do you have any idea what might be going on? 😅 I don't see how this can be related to these changes.
```
[info] ==> X epollcat.TcpSuite.local and remote addresses 0.00s munit.ComparisonFailException: /Users/runner/work/epollcat/epollcat/tests/shared/src/test/scala/epollcat/TcpSuite.scala:133
[info] 132:                assertEquals(clientRemote, serverLocal)
[info] 133:                assertEquals(serverRemote, clientLocal)
[info] 134:              }
[info] values are not the same
[info] => Obtained
[info] /127.0.0.1:49866
[info] => Diff (- obtained, + expected)
[info] -/127.0.0.1:49866
[info] +/0:0:0:0:0:0:7F00:1:49866
```
https://github.com/armanbilge/epollcat/actions/runs/3432632786/jobs/5722112147

I am going to try re-running CI.

**Comment by LeeTibbert** [comment]
Sorry for the belated reply, the at_mention must have slipped past me.

I suspect this is using SN 0.4.8 and the InetAddress changes in it.  True?

I will have to trace.   First thing to check is why an IPv4 address is being represented
in the number of bytes for and IPv6 address.  Should be either 4 bytes (IPv4) or converted
to "::FFFF:" form.

**Comment by LeeTibbert** [comment]
Re-opened??  I thought Issue #88 had been solved.

**Comment by armanbilge** [comment]
@LeeTibbert the purpose of this PR was completely unrelated, it is just where I first stumbled on the "quirk".

If you have a chance, I would appreciate a review 😄

**Comment by LeeTibbert** [comment]
OK back to the program (PR) in progress.   I will take a look at the changed file.

**Comment by LeeTibbert** [comment]
This LGTM 

I did a minimal trace on  the two "go" tailrec methods because it after 
the first two or three readings, it looked like they had moved on the page
and not had any substantive changes.

Using the bulk ByteBuffer methods looks like it should speed things up.
It nothing else, it simplifies the code and makes it easier to follow.

**Review by LeeTibbert — APPROVED** [review]
LGTM

Thank you for the opportunity to review

**Comment by armanbilge** [comment]
> it looked like they had moved on the page
> and not had any substantive changes.

For future reference: I often find it helpful to review with whitespace-only changes "hidden". Helps me identify the real changes and not get lost in indentation :)

Screen Shot 2022-11-18 at 4 53 18 PM

**Comment by LeeTibbert** [comment]
Good info.  I had thought they had moved up & down the page, but I may have been looking at
indentation changes.

**Comment by armanbilge** [comment]
Thanks for the review! Much appreciated, and for all your work on the quirk :)

**Pull request merged**
